apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  name: global-resources
spec:
  quota:
    hard:
      pods: "100"
      requests.cpu: "500m"
      requests.memory: "1Gi"
      limits.cpu: "1000m"
      limits.memory: "2Gi"
  selector:
    matchLabels:
      # Will select projects with the label 'quota-bound' set to 'true'
      # oc label namespace <project-name> quota-bound=true
      quota-bound: "true"
