apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          requests:
            cpu: "5"
            memory: "1Gi"
          limits:
            cpu: "5"
            memory: "1Gi"
